version: '3.8'

services:
  # قاعدة البيانات PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: pharmacy_postgres
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmacy_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # تطبيق Go Backend
  pharmacy_backend:
    build: .
    container_name: pharmacy_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: pharmacy_db
      DB_SSLMODE: disable
      JWT_SECRET: your-secret-key-change-this-in-production
      PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pharmacy_network
    restart: unless-stopped

  # pgAdmin (اختياري - لإدارة قاعدة البيانات)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pharmacy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pharmacy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pharmacy_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  pharmacy_network:
    driver: bridge

